version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    container_name: zookeeper
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
  kafka:
    image: confluentinc/cp-kafka:3.3.0
    container_name: kafka
    network_mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  schema-registry:
    image: confluentinc/cp-schema-registry:3.3.0
    container_name: schema-registry
    network_mode: host
    environment: 
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:32181
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://localhost:8081
    depends_on: 
      - kafka
  kafka-rest:
    image: confluentinc/cp-kafka-rest:3.3.0
    container_name: kafka-rest
    network_mode: host
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_REST_LISTENERS: http://localhost:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://localhost:8081
      KAFKA_REST_HOST_NAME: localhost
    depends_on: 
      - schema-registry
